import type { ScenarioConfig } from '../types';

export const SCRIPTED_SCENARIOS: ScenarioConfig[] = [
  {
    id: 'scripted-1-dawn-recon',
    name: 'Dawn Recon (Tutorial)',
    description: 'Single hostile quadcopter conducting aerial reconnaissance at dawn. Ideal for learning basic detection, EO slewing, and RF jamming.',
    seed: 101,
    difficulty: 1,
    environment: {
      time: 'day',
      weather: 'clear',
      terrain: 'rural',
    },
    sensorDegradation: {
      radarOutage: false,
      rfJitter: false,
      eoFogPenalty: 0,
      falseBlips: false,
    },
    waves: [
      {
        startTime: 3,
        count: 1,
        type: 'hostile_recon',
        behavior: 'loiter_recon',
        spawnRange: 2800,
        speed: 14,
      },
    ],
    duration: 90,
    hints: [
      'Click the radar blip (TRK-101) to select it.',
      'Press [D] or click DETECT to acknowledge the track.',
      'Slew the EO/IR camera towards its bearing to inspect visually.',
      'Classify as Hostile Recon and use [J] RF Jammer when in range.',
    ],
  },
  {
    id: 'scripted-2-convoy-kamikaze',
    name: 'Convoy Kamikaze',
    description: 'High-speed autonomous attack drone making a direct low-altitude raid on base asset at night. Rapid response required!',
    seed: 202,
    difficulty: 3,
    environment: {
      time: 'night',
      weather: 'clear',
      terrain: 'rural',
    },
    sensorDegradation: {
      radarOutage: false,
      rfJitter: false,
      eoFogPenalty: 0.1,
      falseBlips: false,
    },
    waves: [
      {
        startTime: 4,
        count: 1,
        type: 'hostile_attack',
        behavior: 'direct_attack',
        spawnRange: 3000,
        speed: 38,
        isAutonomous: true,
      },
    ],
    duration: 90,
    hints: [
      'Fast attack drone incoming! RF jammer will NOT work on autonomous guidance.',
      'Sound alarm [A] immediately so base personnel take cover.',
      'Use Hard-Kill Kinetic Interceptor [H] to neutralize before impact.',
    ],
  },
  {
    id: 'scripted-3-bird-confusion',
    name: 'Bird & Decoy Confusion',
    description: 'Complex air picture with migratory bird flocks, a local hobbyist drone, and a covert hostile attack drone hiding among decoys.',
    seed: 303,
    difficulty: 5,
    environment: {
      time: 'day',
      weather: 'fog',
      terrain: 'rural',
    },
    sensorDegradation: {
      radarOutage: false,
      rfJitter: true,
      eoFogPenalty: 0.35,
      falseBlips: true,
    },
    waves: [
      {
        startTime: 2,
        count: 3,
        type: 'bird',
        behavior: 'erratic',
        spawnRange: 2200,
        speed: 8,
      },
      {
        startTime: 5,
        count: 1,
        type: 'civilian',
        behavior: 'erratic',
        spawnRange: 1800,
        speed: 10,
      },
      {
        startTime: 8,
        count: 1,
        type: 'hostile_attack',
        behavior: 'direct_attack',
        spawnRange: 2900,
        speed: 28,
      },
    ],
    duration: 100,
    hints: [
      'Radar cross-section (RCS) for birds is very low (<0.01 dBSM).',
      'Verify visual feed before firing to avoid wasting interceptors or causing collateral damage!',
    ],
  },
  {
    id: 'scripted-4-urban-swarm',
    name: 'Urban Swarm Raid',
    description: 'Coordinated 12-drone attack swarm navigating high-rise urban canyons. Buildings cause radar shadow zones and sudden pop-up threats.',
    seed: 404,
    difficulty: 7,
    environment: {
      time: 'day',
      weather: 'rain',
      terrain: 'urban',
    },
    sensorDegradation: {
      radarOutage: true,
      rfJitter: true,
      eoFogPenalty: 0.2,
      falseBlips: true,
    },
    waves: [
      {
        startTime: 5,
        count: 12,
        type: 'hostile_swarm',
        behavior: 'formation',
        spawnRange: 2800,
        speed: 26,
      },
    ],
    duration: 120,
    hints: [
      'Urban buildings block radar signals at low altitudes.',
      'RF Jammer can neutralize multiple RF-linked swarm drones in range!',
      'Sound alarm if swarm breaks through outer perimeter.',
    ],
  },
  {
    id: 'scripted-5-friendly-risk',
    name: 'Friendly Fire Risk',
    description: 'Friendly patrol UAVs with malfunctioning IFF transponders operate in the sector alongside hostile recon and kamikaze drones.',
    seed: 505,
    difficulty: 8,
    environment: {
      time: 'night',
      weather: 'fog',
      terrain: 'mountain',
    },
    sensorDegradation: {
      radarOutage: true,
      rfJitter: true,
      eoFogPenalty: 0.4,
      falseBlips: true,
    },
    waves: [
      {
        startTime: 3,
        count: 2,
        type: 'friendly',
        behavior: 'circling',
        spawnRange: 2200,
        speed: 22,
        iffStatus: 'faulty',
      },
      {
        startTime: 6,
        count: 2,
        type: 'hostile_recon',
        behavior: 'loiter_recon',
        spawnRange: 2600,
        speed: 18,
      },
      {
        startTime: 12,
        count: 2,
        type: 'hostile_attack',
        behavior: 'direct_attack',
        spawnRange: 3100,
        speed: 34,
      },
    ],
    duration: 120,
    hints: [
      'WARNING: Intermittent IFF squawks on friendly UAVs.',
      'Do NOT execute hard-kill without EO/IR visual confirmation or you risk severe fratricide penalties!',
    ],
  },
];
