import type { SimulationState } from '../sim/engine';
import type { SessionResult, EntityEvaluation } from '../types';
import { evaluateEntityDecisionTree } from './decisionTree';

export function calculateSessionScore(
  simState: SimulationState,
  traineeName: string,
  unitName: string
): SessionResult {
  const { scenario, simTime, assetHealth, ammoCount, maxAmmo, entities, tracks, actionRecords, replayFrames } = simState;

  // Evaluate per-entity decision trees
  const entityEvaluations: EntityEvaluation[] = entities
    .filter((e) => simTime >= e.spawnTime)
    .map((e) => evaluateEntityDecisionTree(e, tracks.get(e.trackId), simTime));

  let totalDetScore = 0;
  let totalClassScore = 0;
  let totalEngScore = 0;
  let count = entityEvaluations.length || 1;

  let fratricides = 0;
  let collateralIncidents = 0;
  let missedHostiles = 0;

  entityEvaluations.forEach((evalItem) => {
    totalDetScore += evalItem.detectionScore;
    totalClassScore += evalItem.classificationScore;
    totalEngScore += evalItem.engagementScore;

    if (evalItem.trueType === 'friendly' && evalItem.engagementScore === 0) {
      fratricides++;
    } else if ((evalItem.trueType === 'civilian' || evalItem.trueType === 'bird') && evalItem.engagementScore === 0) {
      collateralIncidents++;
    } else if (evalItem.trueType.startsWith('hostile') && evalItem.engagementScore <= 20) {
      missedHostiles++;
    }
  });

  const avgDetection = Math.round(totalDetScore / count);
  const avgClassification = Math.round(totalClassScore / count);
  const avgEngagement = Math.round(totalEngScore / count);

  // Calculate Efficiency Subscore
  const ammoUsed = maxAmmo - ammoCount;
  const hardKillActions = actionRecords.filter((a) => a.payload?.type === 'hard_kill').length;
  const nonHostileHardKills = actionRecords.filter((a) => {
    if (a.payload?.type !== 'hard_kill') return false;
    const ent = entities.find((e) => e.trackId === a.trackId);
    return ent && !ent.trueType.startsWith('hostile');
  }).length;

  let efficiency = 100 - nonHostileHardKills * 30 - Math.max(0, hardKillActions - 4) * 10;
  efficiency = Math.max(0, Math.min(100, Math.round(efficiency)));

  // Final Overall Score (0-100)
  // Weightings: 25% Detection, 25% Classification, 30% Engagement, 10% Efficiency, 10% Asset Health
  let finalScore = Math.round(
    avgDetection * 0.25 +
      avgClassification * 0.25 +
      avgEngagement * 0.30 +
      efficiency * 0.10 +
      assetHealth * 0.10
  );

  // Deduct heavy penalties for fratricide
  finalScore = Math.max(0, finalScore - fratricides * 25 - collateralIncidents * 10);

  // Letter Grade
  let grade: SessionResult['grade'] = 'F';
  if (finalScore >= 90) grade = 'S';
  else if (finalScore >= 80) grade = 'A';
  else if (finalScore >= 70) grade = 'B';
  else if (finalScore >= 55) grade = 'C';
  else if (finalScore >= 40) grade = 'D';

  // Identify mistake categories
  const mistakeCategories: string[] = [];
  if (fratricides > 0) mistakeCategories.push('Engaged Friendly Asset (Fratricide)');
  if (collateralIncidents > 0) mistakeCategories.push('Wasted Countermeasures on Decoys/Civilians');
  if (avgDetection < 60) mistakeCategories.push('Late Detection of Threat Tracks');
  if (avgClassification < 60) mistakeCategories.push('Misclassified Threat Types');
  if (missedHostiles > 0) mistakeCategories.push('Missed Hostile Attack Drones');
  if (assetHealth < 50) mistakeCategories.push('Asset Perimeter Penetration');

  return {
    id: `sess-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
    traineeName,
    unitName,
    scenarioId: scenario.id,
    scenarioName: scenario.name,
    seed: scenario.seed,
    difficulty: scenario.difficulty,
    timestamp: new Date().toISOString(),
    duration: Math.round(simTime),
    finalScore,
    grade,
    subScores: {
      detection: avgDetection,
      classification: avgClassification,
      engagement: avgEngagement,
      efficiency,
    },
    assetHealthRemaining: Math.round(assetHealth),
    ammoUsed,
    ammoTotal: maxAmmo,
    jammerUses: actionRecords.filter((a) => a.payload?.type === 'jam').length,
    fratricides,
    collateralIncidents,
    missedHostiles,
    entityEvaluations,
    mistakeCategories,
    aiDebriefFeedback: [], // Will be generated by AI instructor
    replayFrames,
    actionRecords,
  };
}
